config/routes.rb
Mildwurm::Application.routes.draw do
  devise_for :users
  resources :articles, :projects do
    resources :images, :videos
  end

  resources :abouts do
    resources :images
  end

  resources :projects do
    resources :members
  end

  match '/contact' => 'pages#contact'
  match '/about' => 'pages#about'
  match '/submit' => 'pages#submit'
  root to: 'pages#about'
end

app/models/article.rb
# this class serves as our basic blog post it has two vals and a relationship
# [name]      The title of the blog post
# [content]   Catchall for raw html
# This class also has_many Image
class Article < ActiveRecord::Base
  default_scope order 'created_at desc'
  has_many :images, dependent: :destroy
  has_many :videos, dependent: :destroy
  attr_accessible :content, :name
end

app/controllers/articles_controller.rb
# Controller for Blog Posts, only admins can edit or create them
# See Article for more info on model
# does standard crud actions
class ArticlesController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  # overwrite index to paginate
  def index
    @articles = Article.page params[:page]
    respond_with @articles
  end

  # simple create method on true sends a good notice
  def create
    flash[:notice] = 'Article Created' if @article.save
    respond_with @article
  end

  # simple update method on success sends a good method
  def update
    flash[:notice] = 'Article Successfully update' if @article.update_attributes! params[:article]
    respond_with @article
  end

  # almost default destroy, on success sends a good message
  def destroy
    flash[:notice] = 'Article Successfully Deleted' if @article.destroy
    respond_with @article
  end
end

app/views/articles/_article.html.haml
%li.article
  %p
    %em.pull-right
      #{article.created_at.strftime("%H:%M").sub! /^0*/, ''}
    %strong
      #{article.created_at.strftime "%B"}, #{article.created_at.mday}
  = markdown article.content
  - if current_user.try :admin?
    %p
      .clearfix
        .btn-group.pull-left
          = link_to 'back', articles_path, class: 'btn'
          = link_to 'edit', edit_article_path(article), class: 'btn btn-primary'
          = link_to 'images', article_images_path(article), class: 'btn'
          = link_to 'videos', article_videos_path(article), class: 'btn'
        = button_to 'destroy', article, method: :delete, class: 'btn btn-danger pull-right'

app/views/articles/_form.html.haml
= form_for article, html: { class: 'text-center' } do |f|
  = render partial: 'shared/form_error', collection: article.errors.full_messages
  %p= f.text_field :name, placeholder: 'name', class: 'input-xlarge'
  %p= f.text_area :content, class: 'input-xxlarge', rows: 15
  = f.submit class: 'btn btn-primary'

app/views/articles/edit.html.haml
= render 'form', article: @article
= render 'shared/author_helper', owner: @article

app/views/articles/index.html.haml
- if current_user.try :admin?
  %p
    .clearfix
      .pull-right
        = link_to 'create article', new_article_path, class: 'btn btn-primary'
%ul.unstyled
  = render @articles
= paginate @articles, theme: 'twitter-bootstrap', pagination_class: 'pagination-small pagination-centered'

app/views/articles/new.html.haml
= render 'form', article: @article
= render 'shared/author_helper', owner: @article

app/views/articles/show.html.haml
%p
  = @article.name
%p
  = markdown @article.content
%p
  .btn-group.pull-left
    = link_to 'back', articles_path, class: 'btn'
    = link_to 'edit', edit_article_path(@article), class: 'btn btn-primary'
    = link_to 'images', article_images_path(@article), class: 'btn'
    = link_to 'videos', article_videos_path(@article), class: 'btn'
= button_to 'destroy', @article, method: :delete, class: 'btn btn-danger pull-right'