config/routes.rb
Mildwurm::Application.routes.draw do
  devise_for :users
  resources :articles, :projects do
    resources :images, :videos
  end

  resources :abouts do
    resources :images
  end

  resources :projects do
    resources :members
  end

  match '/contact' => 'pages#contact'
  match '/about' => 'pages#about'
  match '/submit' => 'pages#submit'
  root to: 'pages#about'
end

app/models/project.rb
# this model is to keep track fo a description, name, and members of each project
# can also have images
# [name]    Title of project
# [content] Description / blurb
#
# has_many Image
# has_many Member
# has_many Video
class Project < ActiveRecord::Base
  default_scope order 'rank desc'
  attr_accessible :content, :name, :rank
  has_many :images, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :videos, dependent: :destroy
end

app/controllers/projects_controller.rb
# Controller for Project Pages, only admins can edit or create them
# See Project for more info on model
# does standard crud actions
class ProjectsController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  # extract main video
  def index
    if @projects.present?
      @showcase_project = @projects.delete_at 0
    end
    render
  end

  # simple create method on true sends a good notice
  def create
    flash[:notice] = 'Project Created' if @project.save
    respond_with @project
  end

  # simple update method on success sends a good method
  def update
    flash[:notice] = 'Project Successfully update' if @project.update_attributes! params[:project]
    respond_with @project
  end

  # almost default destroy, on success sends a good message
  def destroy
    flash[:notice] = 'Project Successfully Deleted' if @project.destroy
    respond_with @project
  end
end

app/views/projects/_form.html.haml
= form_for project, html: { class: 'text-center' } do |f|
  = render partial: 'shared/form_error', collection: project.errors.full_messages
  %p= f.text_field :name, placeholder: 'name', class: 'input-xlarge'
  %p= f.text_area :content, class: 'input-xxlarge', rows: 15
  %p= f.text_field :rank, placeholder: '(highest shows first)'
  = f.submit class: 'btn btn-primary'

app/views/projects/_project.html.haml
%li
  %p
    .clearfix
      .pull-right
        - if project.videos.present?
          = iframe project.videos.first, 250
      %p
        %strong= link_to_unless_current project.name, project
      = markdown truncate(project.content, length: 35)
    - if current_user.try :admin?
      %p
        .btn-group.pull-left
          = link_to 'back', projects_path, class: 'btn'
          = link_to 'edit', edit_project_path(project), class: 'btn btn-primary'
          = link_to 'images', project_images_path(project), class: 'btn'
          = link_to 'members', project_members_path(project), class: 'btn'
          = link_to 'videos', project_videos_path(project), class: 'btn'
      = button_to 'destroy', project, method: :delete, class: 'btn btn-danger pull-right'

app/views/projects/_showcase.html.haml
.row-fluid
  .clearfix
    .pull-left.text-center.clearfix
      - if project.videos.present?
        = iframe project.videos.first
    .pull-left
      %p
        %strong= project.name
      = markdown truncate(project.content, length: 35)
  - if current_user.try :admin?
    %p
      .btn-group.pull-left
        = link_to 'back', projects_path, class: 'btn'
        = link_to 'edit', edit_project_path(project), class: 'btn btn-primary'
        = link_to 'images', project_images_path(project), class: 'btn'
        = link_to 'members', project_members_path(project), class: 'btn'
        = link_to 'videos', project_videos_path(project), class: 'btn'
    = button_to 'destroy', project, method: :delete, class: 'btn btn-danger pull-right'

app/views/projects/edit.html.haml
= render 'form', project: @project
= render 'shared/author_helper', owner: @project

app/views/projects/index.html.haml
- if current_user.try :admin?
  %p
    .clearfix
      .pull-right
        = link_to 'create project', new_project_path, class: 'btn btn-primary'
- if @showcase_project.present?
  = render partial: 'showcase', locals: { project: @showcase_project }
%ul.unstyled
  = render @projects

app/views/projects/new.html.haml
= render 'form', project: @project
= render 'shared/author_helper', owner: @project

app/views/projects/show.html.haml
= render partial: 'showcase', locals: { project: @project }