config/routes.rb
Mildwurm::Application.routes.draw do
  devise_for :users
  resources :articles, :projects do
    resources :images, :videos
  end

  resources :abouts do
    resources :images
  end

  resources :projects do
    resources :members
  end

  match '/contact' => 'pages#contact'
  match '/about' => 'pages#about'
  match '/submit' => 'pages#submit'
  root to: 'pages#about'
end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :content
  has_many :images, dependent: :destroy
end

app/controllers/abouts_controller.rb
# Controller for Project Pages, only admins can edit or create them
# See Project for more info on model
# does standard crud actions
class AboutsController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  # simple create method on true sends a good notice
  def create
    flash[:notice] = 'About Created' if @about.save
    respond_with @about
  end

  # simple update method on success sends a good method
  def update
    flash[:notice] = 'About Successfully update' if @about.update_attributes! params[:about]
    respond_with @about
  end

  # almost default destroy, on success sends a good message
  def destroy
    flash[:notice] = 'About Successfully Deleted' if @about.destroy
    respond_with @about
  end
end

app/views/abouts/_form.html.haml
= form_for about, html: { class: 'text-center' } do |f|
  = render partial: 'shared/form_error', collection: about.errors.full_messages
  %p= f.text_area :content, class: 'input-xxlarge', rows: 15
  = f.submit class: 'btn btn-primary'

app/views/abouts/edit.html.haml
= render 'form', about: @about
= render 'shared/author_helper', owner: @about

app/views/abouts/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th
        content
  %tbody
    - @abouts.each do |about|
      %tr
        %td
          = link_to about.name, about
        %td
          = link_to truncate(about.content), about
= link_to 'create about', new_about_path, class: 'btn btn-primary'

app/views/abouts/new.html.haml
= render 'form', about: @about
= render 'shared/author_helper', owner: @about

app/views/abouts/show.html.haml
%p
  = markdown @about.content
%p
  .btn-group.pull-left
    = link_to 'back', abouts_path, class: 'btn'
    = link_to 'edit', edit_about_path(@about), class: 'btn btn-primary'
    = link_to 'images', about_images_path(@about), class: 'btn'