config/routes.rb
Mildwurm::Application.routes.draw do
  devise_for :users
  resources :articles, :projects do
    resources :images, :videos
  end

  resources :abouts do
    resources :images
  end

  resources :projects do
    resources :members
  end

  match '/contact' => 'pages#contact'
  match '/about' => 'pages#about'
  match '/submit' => 'pages#submit'
  root to: 'pages#about'
end

app/models/member.rb
# This class is used to associate members of projects
# they give their real life name and get associated to what
# project they worked on with midgard productions
#
# [name]  Real World Name
#
# belongs_to Project
class Member < ActiveRecord::Base
  belongs_to :project
  attr_accessible :name
end

app/controllers/members_controller.rb
# this controller handles Members for Project
# otherwise it is standard crud
class MembersController < ApplicationController
  load_and_authorize_resource
  respond_to :html
  before_filter :load_project, except: [:destroy, :show, :edit]

  # narrow down the members loaded
  def index
    @members = @project.memebers
  end

  # create and return to a smart path based on our parent
  def create
    flash[:notice] = 'Member Created' if @project.members << @member
    respond_with @project, @member
  end

  # update and return to a smart path based on our parent
  def update
    flash[:notice] = 'Member Successfully updated' if @member.update_attributes! params[:member]
    respond_with @project, @member
  end

  # destroy and return to our parents member index path
  def destroy
    flash[:notice] = 'Member Successfully Deleted' if @member.destroy
    respond_with @member.project, @member
  end

  protected
    # we need the Project for some routes
    def load_project
      local_params = params
      @project = Project.find local_params[:project_id]
    end
end

app/views/members/_form.html.haml
= form_for [project, member], html: { multipart: true } do |f|
  = render partial: 'shared/form_error', collection: member.errors.full_messages
  %p
    = f.text_field :name
  = f.submit class: 'btn btn-primary'

app/views/members/edit.html.haml
%h2
  Editing Member
= render 'form', project: @member.project, member: @member

app/views/members/index.html.haml
%h2
  Members
%table.table.table-striped
  %thead
    %tr
      %th
        name
  %tbody
    - @members.each do |member|
      %tr
        %td
          = link_to member.name, [member.project, member]
= link_to 'create member', new_project_member_path(@project), class: 'btn btn-primary'

app/views/members/new.html.haml
%h2
  Creating Member
= render 'form', project: @project, member: @member

app/views/members/show.html.haml
%p
  = @member.name
%p
  = member_tag @member.file.thumb.url
%p
  .btn-group.pull-left
    = link_to 'back', project_members_path(@member.project), class: 'btn'
    = link_to 'edit', edit_project_member_path(@member.project, @member), class: 'btn btn-primary'
= button_to 'destroy', [@member.project, @member], method: :delete, class: 'btn btn-danger pull-right'